### ISSUE TITLE
Signupform

### ISSUE THREAD

**Issue by ghost** [forecastxl/prototype#32]
- [x] Create component for rendering base errors (#36)
- [x] Add validation for checkbox (#38)
- [x] Make sure all mappings are correct for returned errors (#38)
